name: jboss_ui
description: cards_bd_ui.

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  group_button: ^3.3.1
  file_picker: ^4.3.0
  objectbox: ^1.3.0
  cupertino_icons: ^1.0.2
  flutter_svg: ^0.22.0
  expandable: ^5.0.1
  http: ^0.13.4
  flutter_riverpod: ^1.0.2
  freezed_annotation: ^0.15.0
  flutter_secure_storage: ^5.0.2
  ffi: ^1.1.2
  get_storage:
  path_provider: ^2.0.9
  animated_toggle_switch: ^0.5.2
  json_serializable: ^6.2.0


dev_dependencies:
  objectbox_generator: ^1.3.0
  objectbox_flutter_libs: ^1.3.0
  build_runner: 
  freezed: 0.15.0+1
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/login.png
    - assets/icons/
    - assets/icons/devices_svg/