name: jboss_ui
description: jboss_ui

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_riverpod: ^2.0.0-dev.9

  json_serializable: ^6.2.0
  json_annotation: ^4.5.0
  freezed_annotation: ^2.0.3

  postgres: ^2.4.3

  flex_color_picker: ^2.5.0
  file_picker: ^4.3.0
  cupertino_icons: ^1.0.2
  flutter_svg: ^1.1.0
  expandable: ^5.0.1
  http: ^0.13.4
  flutter_secure_storage: ^5.0.2
  ffi: ^1.1.2
  path_provider: ^2.0.9
  animated_toggle_switch: ^0.5.2
  bitsdojo_window: ^0.1.2
  toml: "^0.13.1"

dev_dependencies:
  flutter_lints: ^2.0.0
  build_runner:

  objectbox_generator:
  freezed: ^2.0.3
  
  flutter_launcher_icons_maker: "^0.10.2"

  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  windows: true
  image_path: "assets/images/login.png"



flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/login.png
    - assets/icons/
    - assets/icons/devices_svg/